# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, unique=True)),
                ('destination', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=150)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jarrbo_postfix.VirtualDomain')),
            ],
        ),
        migrations.AddField(
            model_name='virtualalias',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jarrbo_postfix.VirtualDomain'),
        ),
    ]
