# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_postfix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualuser',
            name='email',
            field=models.EmailField(default='ton@jarrbo.nl', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
