# Generated by Django 2.0 on 2018-02-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_postfix', '0002_virtualuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualalias',
            options={'verbose_name_plural': 'Aliases'},
        ),
        migrations.AddField(
            model_name='virtualalias',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='virtualuser',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
