# Generated by Django 2.0 on 2018-02-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarrbo_postfix', '0003_auto_20180204_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualalias',
            name='destination',
            field=models.CharField(max_length=100),
        ),
    ]
